apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-k8dash
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /kubernetes-dashboard(/|$)(.*)
        backend:
          serviceName: kubernetes-k8dash
          servicePort: 80
