apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  allInOne:
    options:
      query:
        base-path: /jaeger
  annotations:
    kubernetes.io/ingress.class: haproxy
