apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  allInOne:
    options:
      query:
        base-path: /jaeger
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: observability-jaeger
