apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-k8dash
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - http:
      paths:
      - path: /kubernetes-dashboard
        backend:
          serviceName: kubernetes-k8dash
          servicePort: 80
