kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jelastic
  labels:
    type: local
spec:
  storageClassName: 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
