apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-cert
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx-cert"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - example.com
    secretName: external-domain-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-kubernetes
          servicePort: 80
